export interface CourseListEntry {
  niveau: string;
  sousNiveau: string;
  matiere: string;
}

export const COURSE_LIST: CourseListEntry[] = [
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Education artistique' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Initiation à la lecture' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Initiation à l\'écriture' },
  { niveau: 'Primaire', sousNiveau: 'CI', matiere: 'Initiation aux sciences' },

  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Education artistique' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Initiation aux sciences' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Éveil scientifique' },
  { niveau: 'Primaire', sousNiveau: 'CP', matiere: 'Langue nationale (selon la région)' },

  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Education artistique' },
  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Éveil scientifique' },
  { niveau: 'Primaire', sousNiveau: 'CE1', matiere: 'Langue nationale' },

  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Sciences' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Histoire-Géographie' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Langue nationale' },
  { niveau: 'Primaire', sousNiveau: 'CE2', matiere: 'Education artistique' },

  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Sciences' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Histoire-Géographie' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Langue nationale' },
  { niveau: 'Primaire', sousNiveau: 'CM1', matiere: 'Education artistique' },

  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Français' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Mathématiques' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Sciences' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Histoire-Géographie' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Education civique' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Langue nationale' },
  { niveau: 'Primaire', sousNiveau: 'CM2', matiere: 'Education artistique' },

  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Français' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Mathématiques' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Physique-Chimie' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Histoire-Géographie' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Education civique' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Anglais' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'E.P.S (Éducation Physique et Sportive)' },
  { niveau: 'Collège', sousNiveau: '6ème', matiere: 'Informatique (selon les écoles)' },

  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Français' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Mathématiques' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Physique-Chimie' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Histoire-Géographie' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Education civique' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Anglais' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'E.P.S' },
  { niveau: 'Collège', sousNiveau: '5ème', matiere: 'Informatique' },

  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Français' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Mathématiques' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Physique-Chimie' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Histoire-Géographie' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Education civique' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Anglais' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'E.P.S' },
  { niveau: 'Collège', sousNiveau: '4ème', matiere: 'Informatique' },

  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Français' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Mathématiques' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Physique-Chimie' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Histoire-Géographie' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Education civique' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Anglais' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'E.P.S' },
  { niveau: 'Collège', sousNiveau: '3ème', matiere: 'Informatique' },

  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Français' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Mathématiques' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Physique-Chimie' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Histoire-Géographie' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Education civique' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Anglais' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'E.P.S' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Informatique' },
  { niveau: 'Lycée', sousNiveau: '2nde', matiere: 'Espagnol (facultatif)' },

  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Français' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Mathématiques' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Physique-Chimie' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Histoire-Géographie' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Anglais' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'E.P.S' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Informatique' },
  { niveau: 'Lycée', sousNiveau: '1ère S', matiere: 'Philosophie' },

  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Français' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Mathématiques' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Histoire-Géographie' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Anglais' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'E.P.S' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Philosophie' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Littérature' },
  { niveau: 'Lycée', sousNiveau: '1ère L', matiere: 'Informatique' },

  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Français' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Mathématiques' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Physique-Chimie' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Sciences de la Vie et de la Terre' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Histoire-Géographie' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Philosophie' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Anglais' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'E.P.S' },
  { niveau: 'Lycée', sousNiveau: 'Terminale S', matiere: 'Informatique' },

  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Français' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Mathématiques' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Littérature' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Histoire-Géographie' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Philosophie' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Anglais' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'E.P.S' },
  { niveau: 'Lycée', sousNiveau: 'Terminale L', matiere: 'Informatique' },
]; 