// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avxawbwjraeydwhxvuxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2eGF3YndqcmFleWR3aHh2dXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Nzc3ODgsImV4cCI6MjA2NjA1Mzc4OH0.QkjOFQdeU2HBGb3Rh7ALfT3zShyU3c1ADnQZPaKsLOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);